services:

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8090:8090"
    depends_on:
      - ms-region
      - ms-comuna
      - ms-usuario

  ms-region:
    build: ./region
    container_name: ms-region
    ports:
      - "8084:8084"

  ms-comuna:
    build: ./comuna
    container_name: ms-comuna
    ports:
      - "8085:8085"
    depends_on:
      - ms-region

  ms-usuario:
    build: ./usuario
    container_name: ms-usuario
    ports:
      - "8086:8086"