spring.profiles.active=dev
spring.mvc.pathmatch.use-suffix-pattern=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.hateoas.use-hal-as-default-json-media-type=false
springdoc.default-produces-media-type=application/json